### PR TITLE
Apply raw to cooked ratio to ingredients mass.

### PR DESCRIPTION
**Pull request by n1k0**
[User Story](https://www.notion.so/Introduire-le-rapport-cru-cuit-321b61f10081406fb35b633c4b572975)
[Methodology](https://fabrique-numerique.gitbook.io/ecobalyse/alimentaire/rapport-cru-cuit)

Note: depends on fix in #206

### CODE REVIEW

**Comment by n1k0** [comment]
@paulboosz the patch is deployed at https://ecobalyse-pr205.osc-fr1.scalingo.io/#/food/build, could you please ensure the raw to cooked computations are okay? need to run and won't be working until Monday. Thanks!

**Comment by paulboosz** [comment]
Computations are ok

**Review by paulboosz — APPROVED** [review]
computations are ok

**Review by magopian — APPROVED** [review]
This looks perfect, well done!

**Pull request merged**
