### PR TITLE
Allow adjusting ecotox weighting.

### PR DESCRIPTION
**Pull request by n1k0**
[User Story](https://www.notion.so/Rendre-param-trable-la-pond-ration-de-l-cotox-894d42e217c6448a883346203dff8db4)

### CODE REVIEW

**Review by magopian — COMMENTED** [review]
Looks nice, thanks! I'm worried updating the processes isn't enough though, not sure what you think?

**Comment by n1k0** [comment]
@magopian damn, totally missed that indeed. So… I don't think this feature is achievable without reengineering everything from the ground up, sadly. Or maybe you have an idea how?

**Comment by n1k0** [comment]
I'm about to spend some time implementing this, but I feel like we're doing it wrong

```elm
{-| Update database with new definitions and recomputes processes aggregated impacts accordingly.
-}
updateImpactDefinitions : Definitions -> Db -> Db
updateImpactDefinitions definitions db =
    let
        updatedProcesses =
            db.processes |> updateProcesses definitions
    in
    { db
        | impactDefinitions = definitions
        , processes = updatedProcesses
        , countries = db.countries |> updateCountries updatedProcesses
        , materials = db.materials |> updateMaterials updatedProcesses
        , products = db.products |> updateProducts updatedProcesses
        , wellKnown = db.wellKnown |> updateWellKnown updatedProcesses
    }


updateProcesses : Definitions -> List TextileProcess.Process -> List TextileProcess.Process
updateProcesses definitions =
    List.map
        (\({ impacts } as process) ->
            { process
                | impacts =
                    impacts
                        |> Impact.updateAggregatedScores definitions
            }
        )


updateCountries : List TextileProcess.Process -> List Country -> List Country
updateCountries processes countries =
    countries -- TODO: update all processes there


updateMaterials : List TextileProcess.Process -> List Material -> List Material
updateMaterials processes materials =
    materials -- TODO: update all processes there


updateProducts : List TextileProcess.Process -> List Product -> List Product
updateProducts processes products =
    products -- TODO: update all processes there


updateWellKnown : List TextileProcess.Process -> TextileProcess.WellKnown -> TextileProcess.WellKnown
updateWellKnown processes wellKnown =
    wellKnown -- TODO: update all processes there
```

**Comment by n1k0** [comment]
@magopian I've investigated the options you've listed, and while I agree the third one would probably be the best, I'm on holidays tonight, so I went with the first option, which doesn't look as bad as I thought.

Feel free to approve this patch or take over it while I'm away :)

**Comment by n1k0** [comment]
I've addressed your comments while packing my suitcase. Would be nice to merge this before I leave for a week.

**Review by magopian — APPROVED** [review]
Nice thanks ! 🚢

**Pull request merged**
