### PR TITLE
Use the selected knitting process' waste

### PR DESCRIPTION
**Pull request by magopian**
[user story](https://www.notion.so/Tricotage-adapter-taux-de-perte-8c6226030a734dfc90b3e17216b29b0b) : it was always the default product's knitting process' waste that was used, instead of the selected one's.

### CODE REVIEW

**Review by n1k0 — COMMENTED** [review]
Looks good, though I'm surprised no API parameter and tests have been added?

**Comment by n1k0** [comment]
Hmm sorry I was confused, it's not a new simulation parameter. Though I'd still have expected some tests to break and/or new ones to be added.

**Comment by magopian** [comment]
I added tests, what do you think @n1k0 , is that enough?

**Comment by n1k0** [comment]
Yeah sorry for the latency, added tests are good.

**Pull request merged**
