### PR TITLE
Fix mobile menu

### PR DESCRIPTION
**Pull request by magopian**
Some more DSFR fixes

### CODE REVIEW

**Comment by n1k0** [comment]
Isn't the fix I already pushed to master this morning isn't enough?

**Comment by n1k0** [comment]
I remember we decided with @ccomb a few weeks ago that hotfixes could be pushed to master directly, but I understand watching the repo is painful. So we'll switch back to a "no direct push to master" policy, and I'll configure the repo to reject direct pushes to master as of now.

**Comment by n1k0** [comment]
Hmm I don't think we should stick this much to the dsfr styles, as now the header takes a lot of vertical space, while the app already have to deal with a lot of information density, especially in the simulators… If you feel uncomfortable not strictly sticking to the dsfr guidelines, look at what [aides-territoires](https://aides-territoires.beta.gouv.fr/) does for instance: we can safely expect being "allowed" to do the same, in respect to end users comfort of use of the service.

image

**Comment by magopian** [comment]
as you wish.

**Pull request closed without merging**
