### PR TITLE
Make json with docker

### PR DESCRIPTION
**Pull request by ccomb**
- Makefile in `ecobalyse/data` that uses docker to build json data with pinned versions
- Documentation on how to use it (tested on Linux/amd64 and Mac/arm64)
- New json data generated from Linux/amd64

### CODE REVIEW

**Review by n1k0 — COMMENTED** [review]
I've just run `make` on a M2 Max mbp, and these are the results:

```
Export de 17 ingrédients vers ../../../public/data/food/ingredients.json
Export de 58 procédés vers ../../../public/data/food/processes/builder.json
Terminé.
```

Examining the diff in `builder.json`, I confirm getting a huge difference for PEF values, eg:

```diff
-      "pef": 19.687966691912642
+      "pef": 2812.531712324704
```

This one will indeed be hard to investigate…

**Review by n1k0 — COMMENTED** [review]
Oh, I totally forgot to mention: great work with the containerization, works great! I just wish we could pull `agribalyse3_no_param.CSV.zip` automatically to reduce friction, but great work nonetheless 👍

**Review by n1k0 — APPROVED** [review]
I think this patch is now in a good shape for landing. Great work btw! 👍

**Comment by n1k0** [comment]
Maybe @paulboosz and @magopian would like to approve or comment further though?

**Comment by ccomb** [comment]
J'attends juste 1 approbation de @paulboosz ou @magopian et je fusionne en aplatissant pour avoir juste une ligne dans le changelog

**Pull request merged**
