### PR TITLE
add european flax

### PR DESCRIPTION
**Pull request by paulboosz**

### CODE REVIEW

**Review by n1k0 — APPROVED** [review]
Patch looks good from a code standpoint 👍

**Comment by n1k0** [comment]
@paulboosz any news regarding this patch? Should we land it, does it need updates, or could we close the PR? Thanks.

**Comment by paulboosz** [comment]
We are still waiting for a response. A reminder has been sent

**Comment by n1k0** [comment]
> We are still waiting for a response. A reminder has been sent

@paulboosz any news about this? I suggest we close this PR.

**Pull request closed without merging**
