### PR TITLE
Store split internal value as float

### PR DESCRIPTION
**Pull request by n1k0**
This avoids **internally** rounding percentages while they should not.

### CODE REVIEW

**Review by ccomb — COMMENTED** [review]
Since Splits look like a fraction, couldn't it be implemented as two Int instead of a Float? Such as Split Int Int (33% would be Split 1 3)

**Comment by n1k0** [comment]
@ccomb I think we xwant to keep being able to express splits from floats like `airTransportRatio = Split.fromFloat 0.4576` and finding the equivalent fraction 1. isn't easy and 2. isn't useful.

**Comment by paulboosz** [comment]
Yay for always using float 🙌

**Comment by n1k0** [comment]
Landing with r=@paulboosz

**Comment by ccomb** [comment]
This is because I've long ago been definitely traumatized by the usage of floats in management or accounting applications and the associated unsolvable rounding issues :-/ But ok we're not in accounting.

**Pull request merged**
