### PR TITLE
Take bonuses into account for ecs computation in the API

### PR DESCRIPTION
**Pull request by magopian**
[user story](https://www.notion.so/Afficher-l-ecoscore-bonus-inclus-dans-l-API-8a228998555b49cfb130219d09910dbd)

### CODE REVIEW

**Review by n1k0 — APPROVED** [review]
Perfect 👌

**Comment by magopian** [comment]
ah but yes of course, thank you for the reminder! What do you think abou the entry I added?

**Comment by n1k0** [comment]
@magopian I don't see it 🤔

**Comment by magopian** [comment]
Well surely it's there (now that I pushed it... 😓 )

**Pull request merged**
