### PR TITLE
Update livestock density coefficient to 3000.

### PR DESCRIPTION
**Pull request by n1k0**
[User Story](https://www.notion.so/Int-gration-Ecoinvent-Mix-Chaleur-f250a03d16754bd2b191bc3738f1b4cc)

### CODE REVIEW

**Review by ccomb — APPROVED** [review]

**Comment by paulboosz** [comment]
[User Story](https://www.notion.so/Modifier-le-poids-du-SE-chargement-2f46ae5592e84f139224dddadaee8fb7?pvs=4)

**Comment by n1k0** [comment]
@paulboosz ?

**Comment by paulboosz** [comment]
initial user story link is to another user story :)

**Comment by n1k0** [comment]
@paulboosz I absolutely don't see what you're talking about 

(fixed, thank you)

**Pull request merged**
